name: country_dial_code
description: This package allows you to get the dialing codes and the name of 250 countries.
version: 1.2.0
repository: https://github.com/astudilloalex/dart-country-dial-codes

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.3

dev_dependencies:
  lint: ^2.8.0
  test: ^1.28.0

flutter:
  assets:
    - assets/flags/
